[tasks.buildwasm]
command = "cargo"
args = ["build"]

[tasks.bindgen]
command = "wasm-bindgen"
args = [
  "--target", "web",
  "--out-dir", "dist",
  "./target/wasm32-unknown-unknown/debug/interactive_background.wasm"
]

[tasks.build]
dependencies = [
  "buildwasm",
  "bindgen",
]

[tasks.buildwasm-rel]
command = "cargo"
args = ["build", "--release"]

[tasks.bindgen-rel]
command = "wasm-bindgen"
args = [
  "--target", "web",
  "--out-dir", "dist",
  "./target/wasm32-unknown-unknown/release/interactive_background.wasm"
]

[tasks.build-rel]
dependencies = [
  "buildwasm-rel",
  "bindgen-rel",
]
